### ISSUE TITLE
How can I contact with the 1st author of the paper?

### ISSUE THREAD

**Issue by liumarcus70s** [CenekAlbl/mvus#1]
Hello Cenek,
    Thank you for the amazing work you shared here. I'm very interesting in your research and I have a lot of questions.
    But, my English is very poor,so I think it should be better to discuss my questions with Jintong Li, the first author of the paper, you know, in Chinese.
    I had sent an e-mail to jingtong.li@geod.baug.ethz.ch, but it seems that a wrong address.
    So, could you tell me how can I contact with him?
Yours,
Jianzheng Liu

**Comment by CenekAlbl** [comment]
Hello Jianzheng,

I am glad that you found our work interesting. 

To reach Jingtong, you can try this address - lijing-at-student.ethz.ch 
Unfortunately I do not have any other contact for Jingtong.

Feel also free to me ask any questions at cenek.albl-at-gmail.com .

Best regards,

Cenek

**Comment by liumarcus70s** [comment]
> Hello Jianzheng,
> 
> I am glad that you found our work interesting.
> 
> To reach Jingtong, you can try this address - lijing-at-student.ethz.ch
> Unfortunately I do not have any other contact for Jingtong.
> 
> Feel also free to me ask any questions at cenek.albl-at-gmail.com .
> 
> Best regards,
> 
> Cenek

Thank you very much， It‘s so nice of you!
